# Generated by Django 3.1.3 on 2020-11-12 19:30

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('release_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('age_restriction', models.IntegerField()),
                ('director', models.CharField(max_length=20)),
                ('cast', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('genres', models.ManyToManyField(to='app.Genres')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.movies')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_row', models.IntegerField()),
                ('nr_seat', models.IntegerField()),
                ('surname', models.CharField(max_length=50)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('phone_number', models.CharField(max_length=14, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('date_of_employment', models.DateField()),
                ('seances', models.ManyToManyField(to='app.Seances')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.clients')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.discounts')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.seances')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.seats')),
            ],
        ),
    ]
