# Generated by Django 3.1.3 on 2020-11-12 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='date_of_employment',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
