# Generated by Django 3.1.3 on 2020-11-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201112_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='workers',
            name='phone_number',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='workers',
            name='salary',
            field=models.IntegerField(default=1000),
        ),
    ]
