# Generated by Django 3.1.3 on 2020-11-13 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201112_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seances',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movies'),
        ),
        migrations.AlterField(
            model_name='seances',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rooms'),
        ),
        migrations.AlterField(
            model_name='seats',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rooms'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clients'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.discounts'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seances'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seats'),
        ),
    ]
