# Generated by Django 3.1.3 on 2020-11-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201113_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='surname',
        ),
    ]
