# Generated by Django 3.1.3 on 2020-11-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_seats_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='cast',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(),
        ),
    ]
